### ISSUE TITLE
Not running on Ubuntu with Nvidia gtx 1080 and on Windows with Intel HD Graphics

### ISSUE THREAD

**Issue by anuraagvaidya** [MaiaVictor/WebMonkeys#24]
When I run an example on an Ubuntu machine with GTX 1080 with NVIDIA Cuda and drivers installed, it fails here:

```
TypeError: Cannot read property 'VERTEX_SHADER' of null
    at buildShader (/home/ubuntu/node_modules/webmonkeys/src/WebMonkeys.js:222:36)
    at init (/home/ubuntu/node_modules/webmonkeys/src/WebMonkeys.js:113:16)
    at WebMonkeys (/home/ubuntu/node_modules/webmonkeys/src/WebMonkeys.js:692:12)
    at Object.<anonymous> (/home/ubuntu/gpu_trial/trial1.js:2:38)
```

and on my windows machine,
The process simply exists with this:
`Process finished with exit code -1073741819 (0xC0000005)
`
What could be wrong?

**Comment by VictorTaelin** [comment]
I don't know :( very sad news but I don't think there is anyone maintaining this repo, I made it for an old project but then went to work in something else.

**Comment by sudodaksh** [comment]
this repo depends on node-gl (npm gl), so probably it's an issue because of that.
